// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 
*/
// const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   


  
}; */

const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Guides',
      link: { type: 'doc', id: 'Guides/index' },
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'Guides' }
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: { type: 'doc', id: 'Tutorials/index' },
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'Tutorials' }
      ],
    },
    {
      type: 'category',
      label: 'Cheat Sheets',
      link: { type: 'doc', id: 'Cheat Sheets/index' },
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'Cheat Sheets' }
      ],
    },
    {
      type: 'category',
      label: 'Help',
      link: { type: 'doc', id: 'Help/index' },
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'Help' }
      ],
    },
  ],
};

export default sidebars;
