backend:
  name: git-gateway
  branch: main

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: "guides"
    label: "Guides"
    folder: "docs/guides"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "string"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
